### ISSUE TITLE
Clashes with pyenv

### ISSUE THREAD

**Issue by adamchainz** [FFY00/python-build#101] opened 2020-09-12 10:15 UTC
pyenv brings with it the [python-build](https://github.com/pyenv/pyenv/tree/master/plugins/python-build) tool, which it uses to build python versions from source.

Now I've done `pip install build`, pyenv invokes *this* python-build, and breaks 😢 

Maybe `python-build` could ship only for invoking as `python -m build`? This would have the advantage of always knowing which python binary you were invoking (the same reason [pip recommends using `python -m pip` everywhere](https://adamj.eu/tech/2020/02/25/use-python-m-pip-everywhere/)).

Or maybe pyenv could be convinced to change to `pyenv-python-build` or similar, though probably breaking some peoples' install scripts?

**Comment by pganssle** [comment] 2020-09-12 13:52
That's very unfortunate. We should probably move away from the `python-build ` branding anyway, since the PyPI package called that is something totally unrelated.

Still, we shouldn't eliminate the entry point. There are good reasons to use an entry point, see #3. 

Maybe we can rename the entry point to something else like `pybuild` or `build-package `? Might also be worth seeing if pyenv can be refactored to work without their `python-build ` being on the PATH. It won't help with anyone directly invoking their `python-build `, but maybe it will reduce the conflicts to a point that they are manageable.

**Comment by FFY00** [comment] 2020-09-12 14:59
Yes, I am open to suggestions, I am not sure what is the best way to proceed, I am open to suggestions.

**Comment by gaborbernat** [comment] 2020-09-14 16:28
> pybuild

:shipit: 🚢

**Comment by adamchainz** [comment] 2020-09-14 18:26
`pybuild` seems fine to me.

The name `pybuild` is taken on PyPI but seems abandoned with last release >4 years ago. Perhaps you can ask to take it over to point to this tool.

There are a number of tools on GitHub search called `pybuild` but none seem popular. Most prominently there's `pybuilder`, but I don't think that risks any confusion.

**Comment by sinoroc** [comment] 2020-09-14 18:41
It builds distributions, right? What about a variation of_distbuild_, _builddist_?

**Comment by layday** [comment] 2020-09-15 00:25
"build" and "pybuild" are too generic to be meaningful to people who are not immersed in Python packaging; I think this should be called pyproject-build, and [python-install](https://github.com/FFY00/python-install), should it eventually be adopted, pyproject-install, on the basis that they have been introduced for the new pyproject format.

**Comment by FFY00** [comment] 2020-10-05 23:44
This somewhat relates to the discussion hapening in #42.

If we go with a generic name like `build`, I would the console script being called something like `pypackage-build`.

**Comment by pradyunsg** [comment] 2020-10-06 00:13
I'm kinda in favor of only shipping `python -m build`, mostly to keep the "CLI surface area" smaller.  It's easy to add in an entry point once we see widespread adoption. It's not easy to remove one though.

**Comment by FFY00** [comment] 2020-10-06 00:16
I am totally fine with that. The entrypoint only exists because @pganssle asked IIRC.

**Comment by adamchainz** [comment] 2020-10-06 08:23
I also like just `python -m build`

@pganssle wrote

> There are good reasons to use an entry point, see #3.

As far as I can see from the issue, there's only one issue - lack of support under `pipx`. It could be reasonable for `pipx` to add support for `-m` invocations, as I'm sure python-build wasn't the only tool without an entry point.

**Comment by gaborbernat** [comment] 2020-10-06 10:23
> It could be reasonable for `pipx` to add support for `-m` invocations, as I'm sure python-build wasn't the only tool without an entry point.

This is not possible, because pipx needs to know under what name you want to expose the tool. If the tool does not provide a name, pipx cannot make up one. I'm in strong +1 that this tool needs to provide a console script name.

**Comment by pradyunsg** [comment] 2020-10-06 12:25
Okay, pipx is a strong enough reason for me to also be on board for adding an entry-point. I don't have any opinion on which one is picked / if pyenv is requested to rename stuff etc. :)

**Comment by FFY00** [comment] 2020-10-07 01:22
I have opened #117 which renames the entrypoint script to `pyproject-build`, which I think is a good name.

Let me know if any of you have issues with that name :blush:

**Comment by pradyunsg** [comment] 2020-10-07 09:58
@gaborbernat #117 hasn't merged yet -- so this isn't fixed yet.

**Comment by layday** [comment] 2020-10-07 11:51
Will the PyPI package be renamed as well or will people be instaling build to invoke pyproject-build?  If you're sticking with build, you should consider squatting pyproject-build on PyPI.

**Comment by FFY00** [comment] 2020-10-07 11:53
Yeah, I should create a  `pyproject-build` package that just depends on `build`.

**Comment by layday** [comment] 2020-10-07 12:08
I'm pretty sure that won't work with pipx - how are you going to re-expose the entry point?

**Comment by FFY00** [comment] 2020-10-07 12:41
Okay, so I'll put a `setup.py` there that will say something like this.
```
You were probably looking for 'build'! pyproject-build is a console script exposed by the 'build' project.

$ pip install build
```

**Comment by gaborbernat** [comment] 2020-10-07 12:43
What about just making pyproject-build depend via install_requires to build? (and re-expose the entry point for pipx reasons).

**Comment by FFY00** [comment] 2020-10-07 12:53
That would try to install two of the same entrypints. It might work in pipx, and maybe even in pip (haven't checked) but if I was implementing an installer frontend (which I kinda am :stuck_out_tongue:) I would probably throw an error or ask for user input and that's bad UX so I would like to avoid it.

**Comment by pganssle** [comment] 2020-10-07 14:02
Another option would be to just make a separate package `pyproject-build` that only exposes the entry point.

That _might_ be marginally less confusing for people, since they can do `pipx install pyproject-build` to install the program `pyproject-build`, and they can do `pip install build` if they only want `python -m build`.

**Comment by layday** [comment] 2020-10-07 14:08
The difference between the project name and the entry point will confuse users regardless and I wonder if it wouldn't be better to relocate to 'pyproject-build' on PyPI - nip this in the bud before the package sees wider adoption.

> The downside to this would be the way the version numbers would work. `pyproject-build` would probably effectively never need to change, so it could sit at one version forever while the relevant version number would be the one associated with `build`.

It would still suffer from not being upgradeable by pipx, unless you were to install 'build' (can you install packages without entry points in pipx?) then `inject pyproject-build` in the former's virtual env and expose the entry point, somehow.

**Comment by pradyunsg** [comment] 2020-10-07 14:14
>  The alternative would be always cutting releases at the same time just to bump the version number on `pyproject-build`, and have `pyproject-build` keep an `==` dependency on `build`.

Given the intended use case, I think this'll work best.

**Comment by pradyunsg** [comment] 2020-10-07 14:15
Let's just call the CLI tool `build`. 😈 

*takes off the hat that the devil gave him*

**Comment by gaborbernat** [comment] 2020-10-07 14:22
At the moment I like best renaming the project as a whole to pyproject_build 🤔 And expose only that... And abandon build entirely, we haven't publicly/widely released yet, so might be the best.

**Comment by pganssle** [comment] 2020-10-07 15:04
> At the moment I like best renaming the project as a whole to pyproject_build thinking And expose only that... And abandon build entirely, we haven't publicly/widely released yet, so might be the best.

This also sounds good to me. It is very hard to search for "build", "python build" or even "python-build". I originally didn't like `pyproject_build` or `pyproject-build` because I thought it implied that you _must_ have a `pyproject.toml` file (even though this is very much not true), but if we're going to call modern (PEP 517/518) "pyproject" builds, it's definitely safe to say that this always does a "pyproject build".



> It would still suffer from not being upgradeable by pipx, unless you were to `install build` (can you install packages without entry points in pipx?) then `inject pyproject-build` in the former's virtual env and expose the entry point, somehow.

Yeah, unless `pipx` has a way to say to update all dependencies even if the package version hasn't changed, that would be a problem. If we don't just rename the whole project to `pyproject-build` or `pyproject_build`, then I think the main reasonable option would be to have a "CLI-only" project on PyPI, with versions released in sync with `build`.

I do think it's not terribly unreasonable to have separate packages for the CLI tool and the library, IMO, since it would be nice for things built on top of the library to be able to depend on the version that has no associated CLI, but as with everything there are many usability trade-offs and no perfect solution.

**Comment by FFY00** [comment] 2020-10-07 15:15
The project is supposed to be a Python package builder. At this moment it exposes a PEP517 builder but if Python changes the build process in the future we will add support for that. So I think the project should keep the `build` name.

I think having `pypyoject-build` throw an error saying that the project is named `build` is a good solution. It does not cause a lot of user stress, people would just fix their `pip`/`pipx` install command.

At least that is my opinion, but understand if you don't feel the same.

**Comment by layday** [comment] 2020-10-07 15:49
> The project is supposed to be a Python package builder. At this moment it exposes a PEP517 builder but if Python changes the build process in the future we will add support for that. So I think the project should keep the `build` name.

Do you envisage Python moving away from the pyproject format?  A lot of effort's gone into standardising, and standardising on, PEP 517 and 518 - the possibility that Python will migrate to a new format or standard, which would depart from pyproject so radically that it would no longer be appropriate to call it 'pyproject', is extremely remote and will remain so for many years to come.  That this tool would be adapted for the new format is an even bigger hypothetical.

**Comment by gaborbernat** [comment] 2020-10-07 16:07
You should never say never, but it's highly unlikely we'll move away from pyproject.toml anytime soon. If we need a new way of building we'll likely just change metadata in the ``pyproject.toml``...

**Comment by FFY00** [comment] 2020-10-07 16:33
I can't count the times I have been hit by issues that originated years ago. When setuptools was created we also didn't know we would have to change things in the future. Software changes and so needs change, we simply can't predict the future. The entrypoint name can be easily changed, the project name can't. If `pyproject-build` doesn't make sense anymore we can create a new one and deprecate `pyproject-build`. I'd like to avoid telling users, `pyproject-build` is deprecated, you should now use this *new* tool.

The idea is, if things change in the backend, we will try our best to keep the frontend the same, avoiding breakage. I do not feel comfortable naming the project something as implementation/standard dependent as `pyproject`.

I still think the best approach would be to simply have the `pyproject-build` package tell users to install `build` instead, but I would accept pinning `pyproject-build` to the `build` version.

**Comment by gaborbernat** [comment] 2020-10-07 16:40
> When setuptools was created we also didn't know we would have to change things in the future. Software changes and so needs change, we simply can't predict the future. 

There's a reason this functionality is not part of setuptools. Similarly when things will change it most likely will be breaking enough that we'll need a new name, and can't just swap things under the hood.

> The entrypoint name can be easily changed, the project name can't.

IMHO for not introducing more confusion along users it's prefered for the two to match. Which for me pushes into the direction to go with ``pyproject-build``...

**Comment by FFY00** [comment] 2020-10-07 16:46
> There's a reason this functionality is not part of setuptools. Similarly when things will change it most likely will be breaking enough that we'll need a new name, and can't just swap things under the hood.

We can always try to keep compability, as I said. If compability is not possible to acheive, we can try to have the least ammount of breakage possible.

> IMHO for not introducing more confusion along users it's prefered for the two to match. Which for me pushes into the direction to go with `pyproject-build`...

But the entrypoint is not even the recommended way to run the project, it is just there for pipx.

At this point, I think it would just be better for pipx to gain a `-m`/`--module` argument in `install` so that we could do this.

```
$ pipx install -m build  # install build as module, as opposed to entrypoint
$ pipx -m build  # run the build module
```

**Comment by gaborbernat** [comment] 2020-10-07 16:51
> At this point, I think it would just be better for pipx to gain a `-m`/`--module` argument in `install` so that we could do this.
> 
> ```
> $ pipx install -m build  # install build as module, as opposed to entrypoint
> $ pipx -m build  # run the build module
> ```

If you're voluntering to make it happen 👍

**Comment by layday** [comment] 2020-10-07 17:00
I don't see how adding a bucketload of complexity to pipx is a reasonable alternative to adding one line in your `setup.cfg` simply because we can't seem to settle on a name.

**Comment by FFY00** [comment] 2020-10-07 17:08
The problem isn't as simple just adding a line to `setup.cfg`...

**Comment by adamchainz** [comment] 2020-10-07 17:10
> At this point, I think it would just be better for pipx to gain a -m/--module argument in install so that we could do this.

If you can make that happen it would help other projects using only `-m` entrypoints too.

**Comment by layday** [comment] 2020-10-07 17:26
If a package does not expose as entry point that should be taken as indication that it should not be decoupled from the Python runtime.  It is for this reason that the `pep517` package did not have an entry point.

**Comment by FFY00** [comment] 2020-10-07 17:40
Well, it shouldn't, at least until/if we implement #104. I am not a user of pipx for this project, the entrypoint was just added because it was requested.

Maybe we should just remove it?

**Comment by pganssle** [comment] 2020-10-07 19:18
> I can't count the times I have been hit by issues that originated years ago. When setuptools was created we also didn't know we would have to change things in the future. Software changes and so needs change, we simply can't predict the future. The entrypoint name can be easily changed, the project name can't. If `pyproject-build` doesn't make sense anymore we can create a new one and deprecate `pyproject-build`. I'd like to avoid telling users, the `pyproject-build` project is deprecated, you should now use this _new_ tool.

I feel like this is actually a good reason to not use a super generic name like `build`. I'd say that the chance that we'll stop calling modern builds "pyproject" builds or something (assuming we decide to call them that in the first place) is approximately the same order of magnitude as (or lower than) the chance that we find some fundamental flaw in the approach `build` is taking, and we find that the large existing user base prevents us from making major breaking changes. In other words, there's as good a chance that we will have _no choice_ but to create a new front-end tool with a different name as that the name suddenly seems inappropriate.

> The idea is, if things change in the backend, we will try our best to keep the frontend the same, avoiding breakage. I do not feel comfortable naming the project something as implementation/standard dependent as `pyproject`.

I am happy with other names, though none of the proposals are as searchable as this. I also think that `pyproject` isn't necessarily specific to PEP 517 — this project doesn't even require you to have a `pyproject.toml` file! It's just a tool that builds Python projects, and it uses the modern build standard.

We don't really have a _good_ option here, but I think `build` and `python-build` are among the worst, because they clash with existing stuff, there are folders called `build` dropped into your local directory when you actually run the tool as a side-effect of some backends (which may become a source of bugs in some situations) and it's impossible to search for or refer to. Even if we call it just `build`, people will be forced to call it `python-build` or something in most contexts, and then there will be confusion about what you are supposed to install with `pip`, what the name of the project is, etc.

Assuming we decide to unify the name for the CLI tool and the name for the project, I see 4 reasonable choices:

## `pyproject-build`:

### Downsides
1. It's still pretty generic, and people will likely just add it to the litany of hard-to-distinguish Python tools (`pyenv`, `virtualenv`, `venv`, `pipenv`, `pip`, `pipx`, etc).
2. People may think that you need a `pyproject.toml` to use it (though most people of this sort don't understand what `pyproject.toml` is / does, and are probably using `setup.py` anyway).
3. It may be seen as associated with PEP 517/518/621/etc, but if we later abandon this approach in favor of something else, the name may seem antiquated. For example, if we had built a tool like this 10 years ago, we might have called it 'egg-factory' or something, and even if we later changed it so that `egg-factory` produces only wheels, not eggs, it would be hard to blame people for thinking it was an antiquated tool.

### Upsides

1. Searchable.
2. Pretty obvious that it builds Python packages, rather than Python itself.
3. The CLI tool and the `-m` can be named the same thing.
4. Reasonably easy to remember.

## `python-build`

### Downsides
1. Even more generic.
2. Clashes with `pyenv` (though @adamchainz, how do I repro the issue? When I do `pyenv install 3.9.0` with `build` installed via `pipx`, it seems to work just fine).
3. A project with this name already exists, and actually builds Python rather than building Python packages.
4. Clashes to some extent with the nomenclature of some linux distros (e.g. Debian and Arch), which tend to namespace tools with `python-`. It would have to either be `python-python-build` or `python-build` (even though normally it would be `python-<modulename>`).
5. Decently hard to search for, particularly when search engines like Google will ignore the `-` even if you wrap it in quotes.

### Upsides:
1. CLI name is unique enough.
2. This is already the name people have been using to refer to this project.


## `build`

### Downsides

1. So generic as to be almost meaningless, lacking even the context that this refers to Python. There are almost certainly naming conflicts everywhere.
2. It will be impossible to search for this and references to this even on your own hard drive, since you probably have dozens or hundreds of `build` directories on your computer as a result of building Python projects (or possibly even just random stuff).
3. In order to make the name specific enough that you can actually refer to the project, people will use a different name like `python-build`, which will cause confusion and open us up to typo-squatting.
4. The CLI tool being named `build` seems like a bad idea? I would be shocked if there weren't a bunch of clashes with this, if only in people's bash aliases.

### Upsides

1. Very generic seems more authoritative I guess?

## A name mostly-unrelated to the function, possibly randomly generated or nonsense (e.g. `zewen`, `festun`, `mamongi`)
## Downsides:

1. Name does not convey what it does, so it is an additional thing for people to memorize (e.g. `pip`).
2. May seem less professional than using a much more generic name.

## Upsides:

1. Incredibly searchable
2. No problem with ergonomics or name clashes or confusion.
3. CLI and module can easily be named the same thing.

---

Writing that out, I'm sort of in favor of picking a random name. We could use a Markov chain and come up with a 5-7 letter pronounceable, searchable and unique name. I'm also on board with moving the whole project to `pyproject-build`.

**Comment by pradyunsg** [comment] 2020-10-07 19:31
> Writing that out, I'm sort of in favor of picking a random name.

Ditto. And... with that I'mm cop out of this discussion to avoid the bikeshedding that might follow.

**Comment by FFY00** [comment] 2020-10-07 19:48
I like it being generic, it means that is the project in charge of building Python packages, period. But I guess this might be personal.

But if the name is too confusing for people, maybe we should as proposed above split this into two different projects. `build` would be the library, and something like `pyproject-build` would be the CLI. The two projects could even live in the same repo if that makes sense.

Other possible proposal would be to keep this project as is, with `__main__` exposed and create a new project that implements #104, which would be more suitable for a final user tool. There we could go a little bit more crazy, and lose the "minimal dependencies" rule. Distro packagers and people with similar use-cases would use `build`, end-users would use `pyproject-build`.

There are a lot of opinions here and a lot of people pulling in different sizes, so I think if we compartementeralized things like that we might be able to better apeal to everyone. Personally, I like the 2nd approach more.

I don't know, this is just me spitballing, let me know what you think...

**Comment by henryiii** [comment] 2020-10-07 22:06
I really like `python -m build`, it is clear, simple, and exactly what you mean, and authoritative. How about, _if this gets accepted into PyPA_, proposing `pypa/build` or `pypa/pypa-build` for the repo, `python -m build` for most users, and `pypa-build` for the entry point?

**Comment by pganssle** [comment] 2020-10-07 23:09
> How about, _if this gets accepted into PyPA_

This is essentially a foregone conclusion, I'd say. No one has expressed any opposition to its inclusion and the votes so far are uniformly +1.

> I like it being generic, it means that is the project in charge of building Python packages, period. But I guess this might be personal.
> 
> But if the name is too confusing for people, maybe we should as proposed above split this into two different projects. `build` would be the library, and something like `pyproject-build` would be the CLI. The two projects could even live in the same repo if that makes sense.

Well yes, people do think of it as authoritative if it has a super generic name like this, but at the end of the day no matter what we call it it will sound authoritative because _it will be authoritative_. We'll add it to the tutorials and give talks about how it's the right way to build your packages, and eventually it will enter the lexicon of Python programmers (or it will get rolled into an omnibus tool and be `omnibustool build` or whatever). `npm`, `pip` and to a lesser extent `cargo` are all basically short nonsense phrases that sound authoritative because they've been widely adopted.

Another downside I thought of to using nonsense words is that there's _probably_ a limited appetite for completely arbitrary phrases like that, and if we have `zewen` for builds and `crizor` for installation, people will probably get them confused.

I would really rather we have an entry point and that we not call the project `build`. I'm slightly more positive about keeping the project called `build` and then also having a separate public CLI for it called `pyproject-build` (though I'd like it even more if they were called `pyproject-build` and `pyproject-build-lib`).

**Comment by gaborbernat** [comment] 2020-10-08 14:36
Reflecting on this I think ``pypa-build`` is actually the best we can do, it's going to live under ``pypa/build`` so having it as ``pypa-build`` console script names sounds great to me. And we can keep it as ``python -m build`` otherwise with ``build`` PyPI package name.

**Comment by FFY00** [comment] 2020-10-08 14:39
> Reflecting on this I think `pypa-build` is actually the best we can do, it's going to live under `pypa/build` so having it as `pypa-build` console script names sounds great to me. And we can keep it as `python -m build` otherwise with `build` PyPI package name.

I can agree to moving forward with this. We are never gonna find a perfect solution.

**Comment by layday** [comment] 2020-10-08 15:56
> Reflecting on this I think `pypa-build` is actually the best we can do, it's going to live under `pypa/build` so having it as `pypa-build` console script names sounds great to me. And we can keep it as `python -m build` otherwise with `build` PyPI package name.

Under this proposal, the PyPI project name and package name would be in conflict with the entry point.  Is there a reason why this might be desirable?  I'm not convinced there should be an entry point at all, for my part, if build can only produce wheels for the Python version it's installed under.

**Comment by gaborbernat** [comment] 2020-10-08 16:03
> Under this proposal, the PyPI project name and package name would be in conflict with the entry point. Is there a reason why this might be desirable?

We can't use the project name as console script as it's too general (build). 

> I'm not convinced there should be an entry point at all,

Having an entry-point will allow this tool to be used by pipx as is today, and provides a non ``python -m`` way to invoke it.

> Imagine someone installing build in CI and then proceeding to invoke `pypa-build` for every job in a multi-Python matrix, only to have it churn out the same wheel

Tools can be abused. The issue is not related at all towards the topic. User can do the same via ``python -m build`` too.

**Comment by layday** [comment] 2020-10-08 16:15
> We can't use the project name as console script as it's too general and conflicts with existing tools with a high probability (build).

I undertand that.  The question I am asking is why would you not rename the project to `pypa-build`, so that the project and the entry point align, to avoid unnecessary confusion?

> Having an entry-point will allow this tool to be used by pipx as is today, and provides a non python -m way to invoke it.
> 
> Tools can be abused. The issue is not related at all towards the topic. User can do the same via `python -m build` too.

Surely, if this was an important enough reason not to add an entry point to `pep517` (https://github.com/pypa/pep517/issues/54), it should have *some* bearing on `build`.

**Comment by henryiii** [comment] 2020-10-08 16:22
Modules with dashes in them introduce issues - `pypa-build` vs `pypa_build`, for example. Since the PyPI `build` name is already dedicated to this project, why make the already clear and someone long-to-type `python -m build` even longer?

Personally, I don't see a strong reason for an entry point unless it could target other python versions (which personally I don't care about, there are tools for setting up multiple Python versions already). I have an issue every so often that is solved by telling someone to replace `pip` with `python -m pip` because they user-installed from one place and are now in an environment some other place and pip & python are not aligned. Certainly, I wouldn't worry too much about optimizing it.

> Surely, if this was an important enough reason not to add an entry point

pep517 was never intended to be a user-facing tool. In fact, they thought they could just drop `pep517.build` since it was not supposed to be a user tool (note: there are 500K references to `pep517.build` on GitHub).

**Comment by gaborbernat** [comment] 2020-10-08 16:29
> Personally, I don't see a strong reason for an entry point unless it could target other python versions (which personally I don't care about, there are tools for setting up multiple Python versions already). I have an issue every so often that is solved by telling someone to replace `pip` with `python -m pip` because they user-installed from one place and are now in an environment some other place and pip & python are not aligned. Certainly, I wouldn't worry too much about optimizing it.

I don't want this tool to be installed globally/user level, because tools should always be installed into isolated build environments, so that they don't clash with system packages. This is the problem pipx solves. And once you follow this paradigm you need a console script name so that you don't have to type ``~/.venvs/here-are-my-tool-venvs/bin/python -m build``. Again, we can recommend people to use ``python -m build`` if they install things globally (but I would not recommend that) or to use ``pypa-build`` if they install it in isolated environments.

**Comment by layday** [comment] 2020-10-08 16:32
> pep517 was never intended to be a user-facing tool. In fact, they thought they could just drop `pep517.build` since it was not supposed to be a user tool (note: there are 500K references to `pep517.build` on GitHub).

There are two reasons provided in the first reply of the linked issue.  One is what you mention and the other is what I have mentioned.

> I don't want this tool to be installed globally/user level, because tools should always be installed into isolated build environments, so that they don't clash with system packages. This is the problem pipx solves. And once you follow this paradigm you need a console script name so that you don't have to type `~/.venvs/here-are-my-tool-venvs/bin/python -m build`. Again, we can recommend people to use `python -m build` if they install things globally (but I would not recommend that) or to use `pypa-build` if they install it in isolated environments.

Isolation is orthogonal to the issue of pipx itself being globally installed, which means that pipx itself can only link against _one_ Python runtime.

**Comment by gaborbernat** [comment] 2020-10-08 16:36
> Isolation is orthogonal to the issue of pipx itself being globally installed, which means that pipx itself can only link against _one_ Python runtime.

I don't follow here, you'll need to expand.

**Comment by layday** [comment] 2020-10-08 16:44
> I don't follow here, you'll need to expand. But note, no, pipx itself doesn't need to be globally installed.

Let's assume that you have `pipx` in your path and `pipx` is installed in the user environment, which is how it is installed by default.  It follows that `pipx` uses the Python that is available in the user environment [1].  Assume that you have a Python 3.8 development or a build environment and a Python 3.7 user environment.  Calling `pipx -m build` will invoke `build` in the `pipx` environment which uses Python 3.7.  This is almost certainly not what you want.

[1] I believe it actually uses the Python version which was active at the time when it created its shared venv, but more often than not, this is going to be the user Python.

**Comment by pganssle** [comment] 2020-10-08 16:47
I think there are still compelling reasons to just not name this package `build`, irrespective of the entry point issue. The practical disadvantages of it being named `build` far outweigh any benefits from "it sounds simple and authoritative".

I think I would prefer `pyproject-build` to `pypa-build` (because `pyproject-build` describes what it actually does, and `pypa-build` just describes what github org it lives under), but both of those avoid all the worst disadvantages of the `build` name.

**Comment by FFY00** [comment] 2020-10-08 16:56
> I undertand that. The question I am asking is why would you not rename the project to `pypa-build`, so that the project and the entry point align, to avoid unnecessary confusion?

It is not certain that the project will live under PyPA for all its lifetime. As I pointed how previously, entrypoint names are easily changed, the project name isn't.

> Personally, I don't see a strong reason for an entry point unless it could target other python versions (which personally I don't care about, there are tools for setting up multiple Python versions already). I have an issue every so often that is solved by telling someone to replace `pip` with `python -m pip` because they user-installed from one place and are now in an environment some other place and pip & python are not aligned. Certainly, I wouldn't worry too much about optimizing it.

I agree with you here, but I am not the user for this, and you probably aren't either :stuck_out_tongue:, so I'll defer to @gaborbernat and @pganssle with a warning that I think it may result in confusion for some users. I'd suggest to only expose an entrypoint once/if/when #104 is implemented.

> I think there are still compelling reasons to just not name this package `build`, irrespective of the entry point issue. The practical disadvantages of it being named `build` far outweigh any benefits from "it sounds simple and authoritative".

I think `build` is *fine*, but I can see the problems with it. Similarly, I can also see the problems with the other names.

Anyway, this already resulted in too much bikeshed. I think there is a consensus that no perfect, or near-perfect, solution is possible. And it does seem some of us have diverging opinions.

I'd like to vote to keep the project name, `build`, and rename the entrypoint to `pypa-build`, as @gaborbernat suggested, or `pyproject-build`.

@gaborbernat @pganssle are any of you able to state your final position on the matter? If so, please do so that we can make a final decision.

**Comment by pganssle** [comment] 2020-10-08 17:00
I'm -1 on keeping the `build` name, +1 on the entry point being named `pyproject-build`, and I'd prefer if the module were also named `pyproject_build`.

`build` is easily the worst name of the lot.

**Comment by gaborbernat** [comment] 2020-10-08 17:13
> Calling `pypa-build` (or a theoretical `pipx -m build`) will invoke `build` in the `pipx` environment which uses Python 3.7. This is almost certainly not what you want.

For pure python projects the version you're building under from does not matter. If you're building a project that has C-extensions then it does. However, the isoalted build environment and the python environment build is running under do not have to be the same. The build project might be running under 3.8, but allow you to create isolation environments under python 3.7 or 2.7. ``pypa-build`` could easily get (soon) a ``--python`` flag that allow you to specify the isolation environment (and under what your build is happening). This would follow the logic virtualenv works. You can install it once, and then use it to create different python versions, but defaults to self. This later issue though is only a problem for c-extension project, most libraries are universal though.


> I'd suggest to only expose an entrypoint once/if/when #104 is implemented.

For the sake of universal wheels I'd hope for earlier. To be fare I expect #104 to be implemented soon (next month or so). I vote to not keep ``build``, and strong +1 for ``pyproject-build``, and +1 for ``pypa-build``. So I guess we go with ``pyproject-build`` then?

**Comment by FFY00** [comment] 2020-10-08 17:19
> I vote to not keep `build`, and strong +1 for `pyproject-build`, and +1 for `pypa-build`. So I guess we go with `pyproject-build` then? I'm happy to keep the project name/structure as is.

Can you clarify on the name? I am having difficulties parsing these two parts.

> I vote to not keep `build`

> I'm happy to keep the project name/structure as is.

**Comment by gaborbernat** [comment] 2020-10-08 17:21
The project structure I think we can keep as is, also the ``-m`` name. I don't think we should keep the console script ``build``. I prefer the strongest ``pyproject-build``, but I can also live with ``pypa-build``.

**Comment by FFY00** [comment] 2020-10-08 17:21
> To be fare I expect #104 to be implemented soon (next month or so).

I am probably not going to work on it for the time being, I have already poured a lot of time into this in a stretch to get this moved over to PyPA and neglected some other projects, including some that may impact me financially. I am happy to review and give feedback anyway.

**Comment by gaborbernat** [comment] 2020-10-08 17:22
I'll do this part 👍

**Comment by FFY00** [comment] 2020-10-08 17:23
> The project structure I think we can keep as is, also the `-m` name. I don't think we should keep the console script `build`. I prefer the strongest `pyproject-build`, but I can also live with `pypa-build`.

Okay, thanks for clarifying. And the project name?

> I'll do this part +1

Thanks!

**Comment by gaborbernat** [comment] 2020-10-08 17:32
> Okay, thanks for clarifying. And the project name?

Can remain ``build`` IMHO 🤷 Unless you don't mind in which case can go with @pganssle proposal.

**Comment by FFY00** [comment] 2020-10-08 17:37
I'd prefer it to stay `build`. So I guess we are staying with `build` and renaming the entrypoint to `pyproject-build`.

If anyone has a major reason why we should not proceed with this please let me know now.

**Comment by henryiii** [comment] 2020-10-08 17:51
I like `pyproject-build` as much as `pypa-build`; and I really like `python -m build` over `python -m pyproject_build`!

**Comment by layday** [comment] 2020-10-08 17:57
> It is not certain that the project will live under PyPA for all its lifetime. As I pointed how previously, entrypoint names are easily changed, the project name isn't.

Which is better, maintaining consistency, aiding discovery and abating confusion, or attempting to account for the unlikely eventuality that 'pyproject' is no longer relevant, while this package is?  I find the insistence on using ambiguous, quirky or obscure names for packaging tools baffling; and unless there is very good reason not to, developers should align the package name with the entry point and the project on PyPI.

**Comment by henryiii** [comment] 2020-10-08 18:06
These can't be aligned if there is a dash in the name. `pyproject-build` would be the entry point, `pyproject_build` would be the module. Image if pip was called `pypackage-installer ` / `python -m pypackage_installer`. That alone would probably cause more confusion than just `python -m build` vs. `pyproject-build` when standalone.

I would view "normal" usage as either in a virtual environment or on CI, and both cases its always better to use `python -m`. It doesn't seem to me that pipx is a good candidate for a tool like `pip`, and therefore a good candidate for `build` either? I always felt pipx was more for python packages that wanted to be "standalone" and hide the fact they were in the Python ecosystem.

**Comment by gaborbernat** [comment] 2020-10-08 18:17
``build`` wants to be also standalone. We could have written in Rust, and served its purpose just as well. ``build`` is a frontend, and interacts with the build backends via subprocess calls and the PEP-517 API. It just happens to be implemented in Python.

**Comment by layday** [comment] 2020-10-08 18:29
> These can't be aligned if there is a dash in the name. `pyproject-build` would be the entry point, `pyproject_build` would be the module. Image if pip was called `pypackage-installer ` / `python -m pypackage_installer`. That alone would probably cause more confusion than just `python -m build` vs. `pyproject-build` when standalone.

Is `build` more obvious?  Would you rather imagine that `pypackage-installer`'s package was called `pip` instead of `pypackage_installer`?  Why would you think that a script called `pyproject-build` would import a package called just `build`?  Why would the project not be called the same as the script, which is called the same as the package, with the caveat that Python identifiers cannot contain hyphens?

> `build` wants to be also standalone. We could have written in Rust, and served its purpose just as well. `build` is a frontend, and interacts with the build backends via subprocess calls and the PEP-517 API. It just happens to be implemented in Python.

I don't know what the relevance of writing `build` in another language is - it would not be invocable with `-m` unless it were packaged as an extension.  You wouldn't call the Rust executable 'build', either.

**Closed** 2020-10-08 18:34 UTC
